### ISSUE TITLE
personal API is served from earliest to latest entry

### ISSUE THREAD

**Issue by berli0z** [tracking-exposed/facebook#143]
Personal API is being "served" in reverse order. it would be more useful if paging was in reversed order (latest scraped content served in the first page, skip to go backwards).

**Comment by vecna** [comment]
this should be fixed, please verify

**Comment by berli0z** [comment]
i just tried with personal - semantics, it still serves data from the earliest to the latest entry (https://facebook.tracking.exposed/api/v2/personal/TOKEN/semantics/100-0)

**Comment by vecna** [comment]
it works now; strange condition in which we stumble upon
