### ISSUE TITLE
show most recent available daily results regardless of date

### ISSUE THREAD

**Issue by privatemaker** [tracking-exposed/facebook#144]
When requesting from `/api/v2/personal/token-token/daily/0-3` if there are no results for current day(s) the API return empty `[ ]` this does not allow Reality Check to show anything to a user. tracking-exposed/facebook.tracking.exposed#16

Better solution: return most recent 3 days. Kind of relates to #143

**Comment by vecna** [comment]
This has been implemented in a way:
* at every hour a batch script counts the activity of the last active users
* this imply, if an user create a profile at 4:20, they should have to wait until 5:00 until get some measurement
* now with easy and with small amount of data, can be returned one object for every day of activity. 
* this afternoon is it still unstable, I'm counting numbers from the past days

**Comment by vecna** [comment]
fully completed. please check

**Comment by privatemaker** [comment]
this seems good now and is fixed. thnx
