### ISSUE TITLE
Validate endpoint fails when user has a vanity url

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/facebook#25]
If the user has a vanity URL for their profile, the permalink does **not** contain `?id=` and the requests fails.

This behaviour can be reproduced with the following command:
```bash
curl -X POST -H "Content-Type: application/json"  -d '{
  "html": "",
  "userId": "818251551",
  "permalink": "https://www.facebook.com/agranzot/posts/10154799187231552",
  "publicKey": "HDtoJqDMDsP7hJJqevWGsdhirWaydLzv6XEuU3ofo58i"
}' "http://localhost:8000/api/v1/validate"
```

**Comment by vecna** [comment]
a force push to override the first commit has been done

**Comment by vecna** [comment]
can be reviewed and merged in master
