### ISSUE TITLE
Fix website metadata

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/facebook#39]
This is how facebook.tracking.exposed looks like when shared on Facebook:
 - https://developers.facebook.com/tools/debug/sharing/?q=facebook.tracking.exposed

On Twitter the preview seems not consistent:
![image](https://cloud.githubusercontent.com/assets/134680/21295085/9f2ad1aa-c54d-11e6-89e7-b8858415877a.png)

A starting point is to support Facebook [Open Graph](http://ogp.me/). I don't remember how Twitter handles that

**Comment by Mitch90** [comment]
From this article (in the "Reconciling meta Tags", https://css-tricks.com/essential-meta-tags-social-media/), seems like Twitter is able to read the Open Graph format.
These are the bare minimum tags necessary:
```
<meta property="og:title" content="European Travel Destinations">
<meta property="og:description" content="Offering tour packages for individuals or groups.">
<meta property="og:image" content="http://euro-travel-example.com/thumbnail.jpg">
<meta property="og:url" content="http://euro-travel-example.com/index.htm">
<meta name="twitter:card" content="summary_large_image">
```
Then, I'm quoting the article:

> Reconciling the guidelines for the image is simple: follow Facebook's recommendation of a minimum dimension of 1200x630 pixels and an aspect ratio of 1.91:1, but adhere to Twitter's file size requirement of less than 1MB.

**Comment by vecna** [comment]
I've addressed it at the ß release, but not properly..
```
meta(property="og:url" content="https://facebook.tracking.exposed")
meta(property="og:image" content="https://facebook.tracking.exposed/images/fbtrex_logo.svg")
```
this is not enough, I'll check better the doc linked above

**Comment by vecna** [comment]
Here is why, you need four of them
![image](https://cloud.githubusercontent.com/assets/89555/21313917/7b0ba914-c5db-11e6-8474-d74a271f70ae.png)

**Comment by vecna** [comment]
despite the presence of 
```
    <meta property="og:title" content="facebook.tracking.exposed">
    <meta property="og:type" content="website">
    <meta property="og:description" content="Facebook Tracking Exposed is a web browser addon that collects the stories visible in your Facebook News feed and a website that aggregates that data from all the users who have the addon installed. Our vision is to increase transparency behind personalization algorithms">
    <meta property="og:url" content="https://facebook.tracking.exposed">
    <meta property="og:image" content="https://facebook.tracking.exposed/images/fbtrex_logo.svg">
    <meta property="og:image:type" content="image/svg+xml">
```

seems the preview picture is not update...

**Comment by vecna** [comment]
I see, probably using an SVG is not a smart idea, I'll change to png

**Comment by vecna** [comment]
now looks cool!
