### ISSUE TITLE
supporting more keys for the same user

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/facebook#48]
restructure the onboarding API in the backend.
support more keys per user, communicate them to the users via web, evaluate with @vrde how to signal and communicate these conditions:

* when an user delete localstorage
* when firefox/chrome syncing are used
* if we can communicate condition like "we know your user but you are in a new browser, therefore..."

**Comment by vrde** [comment]
I think this is already handled by the API. If a user does a new onboarding and they register a new key, then a new document with `userId, publicKey` is stored in the database. The only limitation is if we have a `unique` constraint on the `userId`.

Anyway, I'd let the user register as many keys as they want. The same user `x` might have two different browsers, one at work and one at home, both using the extension, and both registered with the same `userId` but different `publicKey`.

What do you think?

**Comment by vecna** [comment]
`userId` has an unique constraint, so at the moment can't work. the API do not support more than one key, and when this will be supported, we'll have also to provide some feedback to the user in their page

**Comment by vrde** [comment]
Do you think we can remove the unique constraint for now? In which part of the API code you check for `userId` and `publicKey` to validate the signature of the payload?

**Comment by vecna** [comment]
is in `lib/events.js` is not yet validated, I had problem in using NaCL and bs58

**Comment by vecna** [comment]
it is working since a while
