### ISSUE TITLE
fbtrex July'17 Introduction

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/facebook#76]
# + fbtrex introduction July’17 +

### What is the problem?

- Facebook has tremendous global reach and influences thinking in many places
- The ways in which FB selects information to be presented to individual users are not well understood
- Algorithms are like social policies; they should be in public discussions, they can’t be imposed.
- Users has been used as rats lab in psychological and social experiment
- There are strong evidences on the impact the algorithm can, and has, in the society
- There is no transparency (with a data policy) from FB
- Facebook claim the complexity of the algorithm it is so huge no engineer can understand or explain the internals, making in the algorithm the perfect _technocratic scapegoat_

### What are the goals

  * Overall
    * Observe, evaluate, and better understand Facebook algorithm, in particular how FB leverages and profits from promoted content.
    * Develop awareness on how Facebook operate the business of promoted content
    * Enable researchers from non-technical fields to analyze the social media
  * For users of FB
    * Enable better understanding a critical issue and its implications
    * Raise awareness around the concept of “algorithm diversity” or “the right to pick your algorithm.”
    * Provide users with a persistent record of their timeline.
  * For research
    * Serve as a neutral actor, reliably providing research-quality data for analysis
    * Engage diverse research audiences to utilize the data, prioritizing and encouraging interdisciplinary approaches.
  * For FB
    * Over the long term, get FB to give users greater transparency and greater agency over how they experience the algorithm.
    * Encourage FB to publish more open data describing the social phenomena happening in the social media

### How we intend to work toward the goals

- Overall, the approach is based on broadly distributed collection of individual user experiences with FB feeds from their respective observation points, utilizing a networks of volunteers and bots
- Using a web-extension, we will collect data on what each user sees on their public timeline. 
- Extract the metadata from the data submitted, and make this dataset available to researchers.
- Produce visualizations and other renderings of how different users experience the FB algorithm.
- Use research findings to inform both advocacy and user education.

### What needs to be done next? 

Overall, we are open to advice, partnership, and collaboration with all interested parties.

Our roadmap includes the following milestones:
  * Improve the software
    * Improve the code of the parsers, small component who extract metadata from the posts seen from the user.
  * Establish community processes
    * Write a  visually and formally clear data policy, explain the life-cycle of the data and where third party and users interact with us in an exemplary way.
    * Write an ethical agreement to
       * permit the third party accessing the database of collected observations, in order to protect the supporters against social media intelligence; 
     * the third party has not to sell, monetize, publish, reuse or analyze and copy outside the scope of the agreed analysis. 
        * As safeguards, the algorithms runs on the database are declared and formalized, we execute the script, providing an API for the owner.
  * Engage and support researchers
    * Provide support for research organizations as early adopters.
    * Presentation at SHA2017 in August, call for engagement (previous presentations here: https://facebook.tracking.exposed/initiatives )

**Comment by digitigrafo** [comment]
Good summary! Working on the top menu, I propose:

1.     Home (some points chosen from summary)
2.     Get Chrome extension (out link)
3.     Impact (can stay in home page? is it slow to load?)
4.     Privacy Statement (maybe not here?)
5.     Initiatives 
6.     About Us/People
7.     The project (summary)
8. VIZ: (are working? link also in Homepage with icons! or images!)
            8.1 realitycheck 
            8.2 revision
            8.3 information diet

Sidemenu of VIZ:
              8.1.1 get the data (raw data, csv) 
              8.1.2 Privacy Statement (here ?)
              8.1.3 Documentation (i suggest or gitbook, or mkdoc to explain how we develop and how the viz are build)
              8.1.4 Contribute  (page with info for jornalist, research, about github, pull request, translation, contact, ..)
              8.1.4 API (? i dont know if there are..)

Footer menu:
        Home
        Initiatives
        About Us/People/contact ?
        The project (summary)
        Contribute

**Comment by lrnzctld** [comment]
Mi sembra un'ottima sintesi, nell'homepage metterei sostanzialmente il testo che hai appena postato, niente di più niente di meno.
In merito al menù, la voce **Get Chrome extension**  merita una posizione privilegiata essendo l'unica call to action che c'è. Per me dovrebbe essere un bottone nell'header, ben visibile, sopra il menù. 
La mia unica preoccupazione riguarda l'intelligibilità dei dati raccolti, intelligibilità agli occhi dell'utente di *fte*. Penso che su questo ci sia un buon margine di miglioramento.

**Comment by vecna** [comment]
@digitigrafo facciamo call ed iteriamoci :)
@lrnzctld intelligibiltà dei dati raccolti è un grande problema, sì. non ho idea di cosa gli si possa dare che non sia troppo generico

**Comment by lrnzctld** [comment]
@vecna Se vuoi ne possiamo parlare assieme, ma ora tra il caldo e gli ultimi lavori non ho la lucidità per una cosa del genere, se ti va ci sono verso la fine di agosto.

**Comment by vecna** [comment]
nota punto 8: il tour è fatto su utenti hardcodati, così che non si condivide l'informazione di utenti personali. le visualizzazioni mostrate nel punto 8 sono le stesse che l'utente vedrebbe nel realitycheck, ma il realitycheck è accessibile solo a chi ha il plugin (che poi, poò condividere la sua viz, ma per i suoi canali)

**Comment by digitigrafo** [comment]
ipotesi uno BOCCIATA:

ESEMPIO clicco su 8.1: 
_Guarda il tuo realitycheck > pagina realitycheck dell'utente
_8 characters DEMO > scegli il caracter > vedi il suo realitycheck

3 tipologie:
A- utente con plugin
B- utente con link x vedere dati tuoi o altrui
C- utente senza plugin
_______________________________NO________________facciam così:

il punto 8 diventa un TOUR demo delle VIZ:

per mostrarle a chi non usa il plugin, x giornalisti e curiosi. ma sempre di personaggidemo.

IL reality test vero è accessibile solo a chi ha il plugin.

**Comment by digitigrafo** [comment]
footer con last update degli altri siti tracking.exposed

**Comment by digitigrafo** [comment]
ok, ho cambiato un po la navigazione, riaggiunto impact ed iniziato a mettere la pagina project.

**Comment by digitigrafo** [comment]
mi listo i prossimissimi passi:

finire di mettere il contenuti in the project

mettere la barra di navigazione anche sopra realitycheck

sistemare la navigazione secodnaria di quella pagina

sistemare la home

**Comment by vecna** [comment]
Implemented with the new homepage structure
