### ISSUE TITLE
Document researcher use case

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/facebook#87]

**Comment by vecna** [comment]
![participatetoresearchgroup](https://user-images.githubusercontent.com/89555/45584512-09fe3680-b8d5-11e8-8807-c7dbaa095ff4.png)

**Comment by vecna** [comment]
https://github.com/tracking-exposed/facebook/wiki/Researchers-API-and-how-to-download-the-data

**Comment by federicoculloca** [comment]
Language corrections:

> If you want to download your data, I suggest you'll mark your contribution...

Should be

> If you want to download your data, I suggest **you mark** your contribution...

---

> "participate in a control group" and made up a sequence...

Should be

> "participate in a control group" and **make** up a sequence...

---

>  If you are testing this feature alone, just don't share it.

Should be

>  If you are testing this feature **all by yourself**, just don't share **the code**.

I have some doubt on "all by yourself", but what was there previously meant "if you're testing just this feature" basically, which I guess was not what was intended.

---

>  these URLs are accessible to everybody which is participating to the research group

Should be

>  these URLs are accessible to **anyone participating in** the research group

---

> simplify the collaboration among researcher which are using multiple profiles

Should be

> simplify the collaboration among researcher**s** **who** are using multiple profiles

---

> The collected data is the recording of the timeline appearing in a user's timeline.

This is a bit contrived. I'm not sure what it means, so I don't have suggestions.

---

> you can access two special URL

Should be

> you can access two special URL**s**

**Comment by vecna** [comment]
ouch, thanks, but is github :P can't you edit the wiki directly so I merge it :P ? I'll do it, thanks (but please consider it next time! ;))
